print("Hello, World!")
name = input("What is your name? ")
print(f"Nice to meet you, {name}!")   
age = input("How old are you? ")
print(f"You are {age} years old.")
ambition = input("What is your ambition? ")
print(f"Your ambition is to {ambition}.")
print(f"hope you achieve your ambition, {name}!")
exit()